#! /bin/sh

sxhkd &
pulseeffects --gapplication-service &
dunst -conf ~/.config/dunst &
sh ~/.config/polybar/launch.sh
picom &
wal -R

/home/tascord/.npm-global/bin/tradni server force &

xsetroot -cursor_name left_ptr

bspc monitor -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "~"
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bash /home/tascord/.config/bspwm/bspwm_colors.sh &bash /home/tascord/.config/bspwm/bspwm_colors.sh &bash /home/tascord/.config/bspwm/bspwm_colors.sh &
